#!/usr/bin/env bash
# Script that installs Nginx server, redirects /redirect_me and customizes 404 not found

# udating packages before performing installation
sudo apt-get -y update
sudo apt-get -y install nginx

# Allows incoming traffic on the standard HTTP port (TCP port 80) 
sudo ufw allow 'Nginx HTTP'

echo "Ceci n'est pas une pag" | sudo tee /usr/share/nginx/html/404.html
newlines="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "27i $newlines" /etc/nginx/sites-available/default
sudo service nginx restart inside and outside the server.
