#!/usr/bin/env bash
# This script configures the Nginx server so that
# /redirect_me is redirecting to another page

# update and install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

sudo sed -i "47i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html


# Test for any syntax error
sudo nginx -t

# Restart the nginx after configuration
sudo service nginx restart
