#!/usr/bin/env bash
#  A symbolic link named default in the sites-enabled directory, pointing to the default configuration file in the sites-available directory

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start

